/**
 * Maps human-readable Bible book names to USFM/API book IDs.
 * Supports variations like "John", "1 John", "1Cor", "1 Cor", etc.
 */
export const BOOK_IDS: Record<string, string> = {
  // Old Testament
  genesis: 'GEN',
  gen: 'GEN',
  exodus: 'EXO',
  exo: 'EXO',
  leviticus: 'LEV',
  lev: 'LEV',
  numbers: 'NUM',
  num: 'NUM',
  deuteronomy: 'DEU',
  deut: 'DEU',
  joshua: 'JOS',
  josh: 'JOS',
  judges: 'JDG',
  judg: 'JDG',
  ruth: 'RUT',
  '1 samuel': '1SA',
  '1samuel': '1SA',
  '1sam': '1SA',
  '2 samuel': '2SA',
  '2samuel': '2SA',
  '2sam': '2SA',
  '1 kings': '1KI',
  '1kings': '1KI',
  '1ki': '1KI',
  '2 kings': '2KI',
  '2kings': '2KI',
  '2ki': '2KI',
  '1 chronicles': '1CH',
  '1chronicles': '1CH',
  '1chron': '1CH',
  '1chr': '1CH',
  '2 chronicles': '2CH',
  '2chronicles': '2CH',
  '2chron': '2CH',
  '2chr': '2CH',
  ezra: 'EZR',
  nehemiah: 'NEH',
  neh: 'NEH',
  esther: 'EST',
  est: 'EST',
  job: 'JOB',
  psalms: 'PSA',
  psalm: 'PSA',
  ps: 'PSA',
  psa: 'PSA',
  proverbs: 'PRO',
  prov: 'PRO',
  ecclesiastes: 'ECC',
  eccl: 'ECC',
  'song of solomon': 'SNG',
  'song of songs': 'SNG',
  songs: 'SNG',
  sng: 'SNG',
  isaiah: 'ISA',
  isa: 'ISA',
  jeremiah: 'JER',
  jer: 'JER',
  lamentations: 'LAM',
  lam: 'LAM',
  ezekiel: 'EZK',
  ezek: 'EZK',
  daniel: 'DAN',
  dan: 'DAN',
  hosea: 'HOS',
  hos: 'HOS',
  joel: 'JOL',
  joe: 'JOL',
  amos: 'AMO',
  obadiah: 'OBA',
  oba: 'OBA',
  jonah: 'JON',
  jon: 'JON',
  micah: 'MIC',
  mic: 'MIC',
  nahum: 'NAH',
  nah: 'NAH',
  habakkuk: 'HAB',
  hab: 'HAB',
  zephaniah: 'ZEP',
  zep: 'ZEP',
  haggai: 'HAG',
  hag: 'HAG',
  zechariah: 'ZEC',
  zec: 'ZEC',
  malachi: 'MAL',
  mal: 'MAL',
  // New Testament
  matthew: 'MAT',
  matt: 'MAT',
  mat: 'MAT',
  mark: 'MRK',
  mar: 'MRK',
  luke: 'LUK',
  luk: 'LUK',
  john: 'JHN',
  joh: 'JHN',
  jhn: 'JHN',
  acts: 'ACT',
  romans: 'ROM',
  rom: 'ROM',
  '1 corinthians': '1CO',
  '1corinthians': '1CO',
  '1cor': '1CO',
  '1co': '1CO',
  '2 corinthians': '2CO',
  '2corinthians': '2CO',
  '2cor': '2CO',
  '2co': '2CO',
  galatians: 'GAL',
  gal: 'GAL',
  ephesians: 'EPH',
  eph: 'EPH',
  philippians: 'PHP',
  phil: 'PHP',
  php: 'PHP',
  colossians: 'COL',
  col: 'COL',
  '1 thessalonians': '1TH',
  '1thessalonians': '1TH',
  '1thess': '1TH',
  '1th': '1TH',
  '2 thessalonians': '2TH',
  '2thessalonians': '2TH',
  '2thess': '2TH',
  '2th': '2TH',
  '1 timothy': '1TI',
  '1timothy': '1TI',
  '1tim': '1TI',
  '1ti': '1TI',
  '2 timothy': '2TI',
  '2timothy': '2TI',
  '2tim': '2TI',
  '2ti': '2TI',
  titus: 'TIT',
  tit: 'TIT',
  philemon: 'PHM',
  phlm: 'PHM',
  phm: 'PHM',
  hebrews: 'HEB',
  heb: 'HEB',
  james: 'JAS',
  jas: 'JAS',
  jam: 'JAS',
  '1 peter': '1PE',
  '1peter': '1PE',
  '1pet': '1PE',
  '1pe': '1PE',
  '2 peter': '2PE',
  '2peter': '2PE',
  '2pet': '2PE',
  '2pe': '2PE',
  '1 john': '1JN',
  '1john': '1JN',
  '1jhn': '1JN',
  '1jn': '1JN',
  '2 john': '2JN',
  '2john': '2JN',
  '2jhn': '2JN',
  '2jn': '2JN',
  '3 john': '3JN',
  '3john': '3JN',
  '3jhn': '3JN',
  '3jn': '3JN',
  jude: 'JUD',
  jud: 'JUD',
  revelation: 'REV',
  rev: 'REV',
};

export function getBookId(bookName: string): string | null {
  const normalized = bookName.trim().toLowerCase().replace(/\s+/g, ' ');
  return BOOK_IDS[normalized] ?? null;
}
